name: DynamicACPlus
version: 1.0.0
main: com.lynx.dynamicacplus.DynamicACPlus
api-version: 1.21
author: itz_arnavfalke197
description: An advanced anti-cheat plugin for Minecraft servers.

commands:
  ac:
    description: Admin command for Dynamic AC+
    usage: /ac <subcommand>
    permission: dynamicac.admin
  login:
    description: Login to your account
    usage: /login <password>
  register:
    description: Register your account
    usage: /register <password>
  dac:
    description: Reload plugin
    usage: /dac reload
    permission: dynamicac.admin.reload

permissions:
  dynamicac.player.notify:
    description: Receives notifications about alt account detections
    default: true
  dynamicac.admin:
    description: Allows access to admin commands
    default: op